---
- name: Backup alle Proxmox VM's
  hosts: proxmox
  gather_facts: false
  collections:
    - community.proxmox

  tasks:
    - name: Start backup van alle VM's op node1
      community.proxmox.proxmox_backup:
        api_host: "{{ api_host }}"
        api_user: test
        api_password: test
        storage: backup_vm
        mode: all
        node: node1
        wait: true
        validate_certs: false